// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmhprjobdsajnreesixc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaHByam9iZHNham5yZWVzaXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjI5OTAsImV4cCI6MjA3MTMzODk5MH0.hXXv9wyX1Z-ogLD6169ZHwHaO2ksxFETZuskj3noxv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});